### Create a new product
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Men jacket",
    "price": 100,
    "description": "A warm jacket"
}


### Get product
GET http://localhost:3000/api/products
Content-Type: application/json

### Get product by id
GET http://localhost:3000/api/products/682b4425d8c09dc9d5f4375f

### Get product by id with query params
GET http://localhost:3000/api/products/by-query?id=682b4425d8c09dc9d5f4375f


### Update product by id
PUT http://localhost:3000/api/products/682b4425d8c09dc9d5f4375f
Content-Type: application/json

{
    "name": "Lenovo Laptop"
}

### Delete product by id
DELETE http://localhost:3000/api/products/682b595fd8c09dc9d5f43765


