version: '3.8'

services:
  app:
    build: ./server
    container_name: docker-node-app
    ports:
      - "5000:5000"
    environment:
      - USE_DB_SOURCE=atlas
      - MONGO_URL_ATLAS=mongodb+srv://kogimurio:8ZjR1H61OG2rnQF7@clustermongodb.nxvejnh.mongodb.net/E-CommerceDataBase
    depends_on:
      - client

  client:
    build: ./client
    container_name: docker-react-app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
